### ISSUE TITLE
Add fan to Quick Action domain

### ISSUE THREAD

**Issue by UPEngineer** [LAB02-Research/HASS.Agent-Integration#10]
Love the quick actions but I cannot add my fans to them as they are in the fan domain. For example, my office fan is shown as fan.office_fan in HA. Would be nice to be able to use hotkeys to control it.

If there is a currently a way to do it, I can't seem to find it.

Thank you.

**Comment by LAB02-Admin** [comment]
Hi @UPEngineer, this is the repo for the integration, not hass.agent :)

Anyway, that's correct, but I'm actually rewriting the entire quickactions module currently. The next version will pull all domains dynamically, so it'll be fixed then!
