### ISSUE TITLE
Actionable notifications actions don't work

### ISSUE THREAD

**Issue by cromelex** [LAB02-Research/HASS.Agent-Integration#20]
Hi, currently having an issue with Notifications part of the integration.

I have started using actionable notifications. They work fine on my Android phone.
However, when I send them to the HASS.Agent, I get the proper notification with the action buttons, but clicking the buttons does not trigger any action.

I've tried multipl times and it just doesn't work. The same notification can be actioned without issues from a Android device.

**Comment by fillefilip8** [comment]
The event for actionable notifications is different than what the Home Assistant mobile app uses.

See documentation here: [Actionable Notifications](https://hassagent.readthedocs.io/en/latest/notifications/new/notification-actionable/) at the section "Action Automations".

**Comment by cromelex** [comment]
Hi fillefilip8,

Thanks for the feedback.
When I read the documentation earlier (well, skimmed over it) I only really read this bit, so i just plugged my existing notification scripts on the hass agent notify.

_HASS.Agent's actionable notifications work the same way as the companion apps do. Read HA's docs for more info,_

 As it worked for the standard notifications and getting the actions, I assumed it was a bug rather than looking into the specific examples in the documentations.

Sure, if it followed the exact same format as the Home Assistant mobile app it would be ideal as it would save me time but in this case this is just user error.

Closing the issue.
