### ISSUE TITLE
Hass Agent

### ISSUE THREAD

**Issue by Stuartyboy75** [LAB02-Research/HASS.Agent-Integration#34]
Hi

I has HASS agent running on one pc everything is working notifications etc, i have installed on another pc but showing in Home Assistant its showing unavailable and cannot send notifications. MQTT seems to be working okay. I have uninstalled cleared all app files and reinstalled still the same.

**Comment by DrR0X-glitch** [comment]
Did you manage to fix this issue? Otherwise I'm happy to help.

**Comment by Stuartyboy75** [comment]
I got it fixed.

Thank you

**Comment by Stuartyboy75** [comment]
Closed resolved my issue

**Comment by DrR0X-glitch** [comment]
Do you remember what you did? Just a mixture of restarts and reinstalls?

**Comment by Stuartyboy75** [comment]
Hi

Was because there was mqtt data referenced against that machine so used MQTT explorer and found old references for that machine deleted them.

I had removed HASS agent before i done this then reinstalled starting working.

**Comment by DrR0X-glitch** [comment]
Okay cool, thanks for the info
