### ISSUE TITLE
Combined integration broke for those that had it before mediaplayer/notification were added

### ISSUE THREAD

**Issue by gdgeist** [LAB02-Research/HASS.Agent-Integration#39]
@fillefilip8 this combining of integrations broke the existing operating for those that had this already installed.   No review of recent tickets.  Is this being abandoned?

The original sensors and actions no longer work/appear i.e. the entities disappeared and wont add upon remove of integration readd.

**Comment by fillefilip8** [comment]
Existing installations with the previous custom components for Home Assistant. Notification and Media Player. They still work fine.

This repo contains the new integration which combines the functionality of those previous ones + more features.

You cannot import anything from the old ones. You have to start over

**Comment by gdgeist** [comment]
Yes starting over still results in no extra entities - see the other issues.
Deleting/unconfiguring the devices then removing the HASS agent via HACS -> reboot. Add HASS agent via HACS still results in only the media player entity.  Restarting / reconfiguring the HASS agent on the remote PC's  makes no difference.

[home-assistant_hass_agent_2023-10-28T03-02-54.568Z.log](https://github.com/LAB02-Research/HASS.Agent-Integration/files/13194295/home-assistant_hass_agent_2023-10-28T03-02-54.568Z.log)

**Comment by gdgeist** [comment]
MQTT receives only the mediaplayer and device information.  The device information contains no sensor/commands:  

MQTT device Topic:
hass.agent/devices/ARCADECABINET
`{"serial_number":"xxxxxxxxxxxxxxxxxxxxxxxxxxxx","device":{"identifiers":"hass.agent-ARCADECABINET","manufacturer":"LAB02 Research","model":"Microsoft Windows NT 10.0.19045.0","name":"ARCADECABINET","sw_version":"2022.14.0"},"apis":{"notifications":true,"media_player":true}}`

MQTT mediaplayer topic:
hass.agent/media_player/ARCADECABINET/state
`{"duration":0,"currentposition":0,"state":"Off","volume":0,"muted":false}`

The API connection Home Assistant via long term token is configured, tested via the test button and HASS agent retrieves API data from the HASS instance.

Post the update to the HASS Agent integration to include the media player a reinstall repeatedly does not result in anything other than the media player being the result of a "configuring" of a discovered remote agent.

**Comment by gdgeist** [comment]
Apologies for the cycles wasted here.  On my part I could have spent this time writing a pull request for the documentation to clearly call out that the sensors / actions will show up under the Home Assistant topic in MQTT not the agent topic and will be entities listed in the MQTT integration not the HASS Agent integration.
