### ISSUE TITLE
Bug: media_player entity not showing up in Music Assistant integration

### ISSUE THREAD

**Issue by Protoncek** [LAB02-Research/HASS.Agent-Integration#6]
I'm playing with "Music Assistant" integration and it doesn't find new "Hass.Agent" integration's created media player. It does find old "Hass Agent MediaPlayer" integration's player, though.
If i run playback in developer tools new media player works fine. But, as said, Music Assistant can't find it. Since at long run Hass Agent MediaPlayer integration will become ...well, maybe even obsolete and removed i guess, this is a problem...

Any clues?

**Comment by LAB02-Admin** [comment]
Thanks for letting me know, I'm able to reproduce this but not quite sure why it's not seeing it (yet). I'll wait for tomorrow's release, since that'll be able to support the new 2022.11 release of MA, see if that fixes it. Otherwise I'll open a ticket with the devs.

**Comment by Protoncek** [comment]
Thanks a lot!

**Comment by Protoncek** [comment]
Additional info: I found out that above media player is not the only one which doesn't allow to be added - i have three tablets, running Fully kiosk and fully integration in HA, which among others creates media player and it also doesn't allow to be added (picture). 

<img width="475" alt="image" src="https://user-images.githubusercontent.com/26406640/199289499-53196e9e-d777-42b2-a51b-400de365e5e5.png">

**Comment by LAB02-Admin** [comment]
Interesting, thanks for the followup

**Comment by LAB02-Admin** [comment]
No dice, I'll open a ticket with the devs

**Comment by LAB02-Admin** [comment]
Dev mentioned that `set_volume` needs to be implemented, and that does indeed fix it.

HASS.Agent needs an update for that as well though, so this'll be implementeed in the next beta release :)

**Comment by LAB02-Admin** [comment]
The beta is released if you want to test: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.14.0-beta1

You'll also need to update the integration to the latest version (2022.11.9)

Afterwards, it should show up in Music Assistant

**Comment by Protoncek** [comment]
Yep. it does show up. Thanks!

**Comment by LAB02-Admin** [comment]
Great 😀
