### ISSUE TITLE
HASS.Agent Integration Installation instructions

### ISSUE THREAD

**Issue by pedjas** [LAB02-Research/HASS.Agent-Integration#7]
This is all what is said about it in installation instructions. "To use notifications and/or the mediaplayer functionality, you'll need to install the HASS.Agent integration. This can be done through HACS or manually. "

Can you provide installation instructions for us who are not that familiar with Home Assistance platform so we cannot do it like an experts?

**Comment by LAB02-Admin** [comment]
I'm a single dev who has to write all the actual code ánd the docs ánd provide support, all in my spare time, so I can't write out everything in detail. 

There is already a lot of information available on Google about HACS, and they have a guide on how to install:

https://hacs.xyz/docs/setup/prerequisites

If you don't want to use HACS, copy the [hass_agent folder](https://github.com/LAB02-Research/HASS.Agent-Integration/tree/main/custom_components) into the `config\custom_components` folder of your Home Assistant instance, and restart HA.

For the record; if you need help, it doesn't hurt to ask nicely.

**Comment by pedjas** [comment]
Sorry, I did not mean to sound rude. It was just I could not find details about installation.

**Comment by bharvey88** [comment]
I agree it was not clear in the readme to go to HACS and search for the three integrations and add them there. I don't think pedjas was rude either, he clearly explained his issue without being condescending or using any negative wording. I believe a simple sentence at the top of https://github.com/LAB02-Research/HASS.Agent-Integration page saying "please go to HACS and search "HASS." and then download the three integrations then restart home assistant" is all that is needed for us to understand the correct installation workflow. Thanks for your time!

**Comment by LAB02-Admin** [comment]
@pedjas & @bharvey88 - I must've misread then, sorry. 

I'm in the process of improving the documentation after the last update (since it changed a lot), I'll also add a 'integration installation' page.

@bharvey88: you only need the [new integration](https://github.com/LAB02-Research/HASS.Agent-Integration), you can remove the other two (it combines and supersedes the other two).

**Comment by LAB02-Admin** [comment]
Added
