### ISSUE TITLE
media controls not working

### ISSUE THREAD

**Issue by MeowRay** [LAB02-Research/HASS.Agent-Integration#9]

**Comment by LAB02-Admin** [comment]
Too little information, but possible duplicate of [[#229](https://github.com/LAB02-Research/HASS.Agent/issues/229)]

**Comment by MeowRay** [comment]
> Too little information, but possible duplicate of [[#229](https://github.com/LAB02-Research/HASS.Agent/issues/229)]

Media controls do not work when used as a media source for "Music Assistant",
There also seems to be no way to pause/stop when playing a media file directly
